const meetingFields = [
    {
        name: "agenda",
        label: "Agenda",
        type: "text",
        backendType: "String",
        isTableField: true,
        validation: [{ require: true, message: "Agenda is required" }],
    },
    {
        name: "location",
        label: "Location",
        type: "text",
        backendType: "String",
        isTableField: false,
        validation: [],
    },
    {
        name: "related",
        label: "Related To",
        type: "text",
        backendType: "String",
        isTableField: true,
        validation: [],
    },
    {
        name: "dateTime",
        label: "Date & Time",
        type: "datetime",
        backendType: "String",
        isTableField: true,
        validation: [{ require: true, message: "Date & Time is required" }],
    },
    {
        name: "notes",
        label: "Notes",
        type: "textarea",
        backendType: "String",
        isTableField: false,
        validation: [],
    },
    // {
    //     name: "createBy",
    //     label: "Created By",
    //     type: "reference",
    //     backendType: "ObjectId",
    //     isTableField: true,
    //     validation: [{ require: true, message: "Created By is required" }],
    // },
    {
        name: "timestamp",
        label: "Time Stamp",
        type: "datetime",
        backendType: "Date",
        isTableField: true,
        validation: [],
    },
];
exports.meetingFields = meetingFields;